name: Context demo
on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "User Name"
        required: true
        type: string
jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input Balue - ${{ inputs.user_name }}"
      - run: echo "Event - ${{ github.event_name }}"
      - run: echo "Job Status - ${{ job.status }}"
